import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { 
	MatButtonModule, 
	MatToolbarModule,
	MatGridListModule,
	MatCardModule,
	MatFormFieldModule,
	MatInputModule,
  MatSnackBarModule,
  MatIconModule,
  MatExpansionModule,
  MatDatepickerModule,
  MatTooltipModule,
	MatBadgeModule,
  MatProgressSpinnerModule,
  MatStepperModule,
  MatSelectModule,
  MatTableModule,
  MatSortModule,
  MatPaginatorModule,
  MatDialogModule,
  MatSlideToggleModule,
  MatListModule,
  MatButtonToggleModule,
  MatMenuModule} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatButtonModule,
    MatToolbarModule,
    MatGridListModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSnackBarModule,
    MatIconModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatTooltipModule,
    MatBadgeModule,
    MatProgressSpinnerModule,
    MatStepperModule,
    MatSelectModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatListModule,
    MatButtonToggleModule,
    MatMenuModule
  ],
  declarations: [],
  exports: [
  	MatButtonModule,
  	MatToolbarModule,
  	MatGridListModule,
  	MatCardModule,
  	MatFormFieldModule,
  	MatInputModule,
    MatSnackBarModule,
    MatIconModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatTooltipModule,
    MatBadgeModule,
    MatProgressSpinnerModule,
    MatStepperModule,
    MatSelectModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatListModule,
    MatButtonToggleModule,
    MatMenuModule
  ]
})
export class MaterialModule { }
